// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64PLMZhrbyKD4_1sBDX1wckzo7XU0fuw',
    appId: '1:231818879705:android:e105a51e69ed9bed1e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJv16GN0r_TbfdjrXIFXwRVwjUd5Rruc',
    appId: '1:231818879705:ios:b1dd26eea54306681e54c8',
    messagingSenderId: '231818879705',
    projectId: 'flutter-training-app-46c4a',
    databaseURL: 'https://flutter-training-app-46c4a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-training-app-46c4a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}